### PR TITLE
adjust build settings so that Research, BridgeSDK and BridgeSDK_Test …

### PR DESCRIPTION
**Pull request by kalperin**
…are not embedded when building the BridgeApp (iOS) target)

### CODE REVIEW

**Comment by kalperin** [comment]
@syoung-smallwisdom let's hold off on this for a moment.  I need to also change the version number to get around this error:

> ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString 'v4.0' in the Info.plist file at '${bundlePath}' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"

**Comment by kalperin** [comment]
@syoung-smallwisdom, ok this is updated. Thanks!

**Comment by syoung-smallwisdom** [comment]
@kalperin I have a PR against your branch that fixes the build issues with merging this.

**Comment by syoung-smallwisdom** [comment]
See https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/191

**Pull request closed without merging**
